version: "3.8"

services:
    mongodb:
        image: mongo
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./docker-data/mongodb/data/db:/data/db
        ports:
            - "27017:27017"

    redis:
        image: redis
        container_name: redis
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker-data/redis/data:/data

    mysql:
        image: mysql:8.0
        container_name: mysql
        ports: "3306:3306"
        volumes:
            - ./docker-data/mysql/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            -

    nats:
        image: nats
        container_name: nats
        hostname: nats
        ports:
            - "4222:4222"
            - "8222:8222"
        # command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 -js"
        command: "--http_port 8222 -js"


    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
        ports:
            - "22181:2181"

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0